export enum ErrorCode {
  // --- Authentication & Authorization ---
  INVALID_REQUEST = "INVALID_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  PHONE_ALREADY_REGISTERED = "PHONE_ALREADY_REGISTERED",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",

  // --- Devices ---
  DEVICE_ALREADY_REGISTERED = "DEVICE_ALREADY_REGISTERED",
  DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND",

  // --- Messaging ---
  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  MESSAGE_SEND_FAILED = "MESSAGE_SEND_FAILED",
  ATTACHMENT_TOO_LARGE = "ATTACHMENT_TOO_LARGE",
  UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE",

  // --- Contacts / Connections ---
  CONTACT_ALREADY_CONNECTED = "CONTACT_ALREADY_CONNECTED",
  CONTACT_REQUEST_PENDING = "CONTACT_REQUEST_PENDING",
  CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND",

  // --- Group / Channel ---
  GROUP_NOT_FOUND = "GROUP_NOT_FOUND",
  GROUP_JOIN_FAILED = "GROUP_JOIN_FAILED",
  GROUP_PERMISSION_DENIED = "GROUP_PERMISSION_DENIED",

  // --- System / Server ---
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  CACHE_ERROR = "CACHE_ERROR",
  SOCKET_ERROR = "SOCKET_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // --- Third-party / Integration ---
  PUSH_NOTIFICATION_FAILED = "PUSH_NOTIFICATION_FAILED",
  SMS_SEND_FAILED = "SMS_SEND_FAILED",
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
}
